// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDToMoHvmJMBdQzDS-E6qi1KSIeBlubA8',
    appId: '1:785594037013:android:e3294df80a14539c73ef1c',
    messagingSenderId: '785594037013',
    projectId: 'lab08-265ee',
    storageBucket: 'lab08-265ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMY_MXHK1Jy7GhXU4i0PTrfCbkoSvmA-Q',
    appId: '1:785594037013:ios:63158fa67910993d73ef1c',
    messagingSenderId: '785594037013',
    projectId: 'lab08-265ee',
    storageBucket: 'lab08-265ee.appspot.com',
    iosClientId: '785594037013-o7866hspgbh10r5jf7mju08s4hl9184g.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMY_MXHK1Jy7GhXU4i0PTrfCbkoSvmA-Q',
    appId: '1:785594037013:ios:63158fa67910993d73ef1c',
    messagingSenderId: '785594037013',
    projectId: 'lab08-265ee',
    storageBucket: 'lab08-265ee.appspot.com',
    iosClientId: '785594037013-o7866hspgbh10r5jf7mju08s4hl9184g.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab08',
  );
}
